---
title: "UB theme"
author: "Laurent Bergé"
date: "21-04-2022"
output: html_document
---

<style type="text/css">
body {
  font-size: 13pt;
}
</style>

# The website of the unofficial Xaringan theme of the University of Bordeaux

Hi, I'm [Laurent Bergé](https://sites.google.com/site/laurentrberge/), and that's the page of a Xaringan theme I created. I hope it can be useful. It's MIT licensed so feel free to do whatever you want with it.

### Tutorial

[Here](UB_tutorial.html) is a set of slides presenting the main features of the theme. 

The source code of the presentation is [here](https://github.com/lrberge/ub_theme/blob/main/UB_tutorial.Rmd).

### Why another theme?

In the Fall 2021, fresh from having obtained a tenured position at the University of Bordeaux, I had to prepare new courses. 

I finally decided to ditch Beamer for my courses (and Gosh I like Beamer) to start working with HTML presentations, i.e. Xaringan. 

Why change? I'm not proud to say that the main motivating reason was to add GIFs in my presentations.... 

The transition quickly revealed to be painful however. I wanted the stuff to look in a certain way and knew I had to invest a bit of time on customization. I thought my journey was only about writing a few lines of CSS code. I couldn't be more wrong.

My main source of frustration was the figure heights. Most of the time my figures were too tall, kicking the text out of the scene. I ended up with a constant feeling of bullying, unable to add a new figure without fear. Looks silly, right? Don't laugh, that really drove me nuts!

The problem is: you can't get around the figure height problem with just CSS. So I had to roll up my sleeves and start dealing directly with the fellow having all the powers: javascript. That was a rocky trip since it was the first time I really wrote JS code. I learned a lot. And now the heights are automatically adjusted.

Along the way, as I harnessed the power of javascript, I included more and more features. Although I parted with it, Beamer still lives in my heart and you may notice that some of these features only stem from Beamer nostalgia. 

That's the story. A few thousand lines of code, dozens of hours... just to place a few GIFs in a presentation.









